---
driver:
  name: vagrant
  customize:
    memory: 6144
    cpuexecutioncap: 50

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

platforms:
  - name: windows-2012r2
  - name: windows-2008r2
  - name: windows-7
  - name: windows-81
  - name: windows-10
  - name: centos-6.7
  - name: centos-7.1
  - name: centos-7.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: opensuse-13.2

suites:
  - name: webgis
    driver:
      network:
        - ["forwarded_port", {guest: 6080, host: 16080}]
        - ["forwarded_port", {guest: 6443, host: 16443}]
        - ["forwarded_port", {guest: 7443, host: 17443}]
      synced_folders:
        - ["/windows_setups/ArcGIS_Server", "C:/temp/setups/ArcGIS_Server"]
        - ["/windows_setups/ArcGIS_DataStore", "C:/temp/setups/ArcGIS_DataStore"]
        - ["/windows_setups/Portal_for_ArcGIS", "C:/temp/setups/Portal_for_ArcGIS"]
        - ["/windows_setups/ArcGIS_WebAdaptorIIS", "C:/temp/setups/WebAdaptorIIS"]
        - ["/net/metro/Released/Authorization_Files/Version10.5/ArcGIS_Server/Advanced", "C:/temp/auth_files/ArcGIS_Server"]
        - ["/net/metro/Released/Authorization_Files/Version10.5/Portal_for_ArcGIS", "C:/temp/auth_files/Portal_for_ArcGIS"]
        - ["/data", "C:/temp/data"]
    run_list:
      - recipe[arcgis-server::webgis_validate]
      - recipe[arcgis-server::system]
      - recipe[arcgis-server::iis]
      - recipe[arcgis-server::server]
      - recipe[arcgis-server::server_wa]
      - recipe[arcgis-server::datastore]
      - recipe[arcgis-server::portal]
      - recipe[arcgis-server::portal_wa]
      - recipe[arcgis-server::federation]
      - recipe[arcgis-server::services]
      - recipe[arcgis-server::webgis_uninstalled]
      - recipe[arcgis-server::clean]
    attributes:
      chef_client:
        config:
          log_level: ":debug"
      arcgis:
        version: "10.5"
        hosts:
          test.com: ""
        server:
          setup: "C:\\temp\\setups\\ArcGIS_Server\\Setup.exe"
          authorization_file: "C:\\temp\\auth_files\\ArcGIS_Server\\Server_Ent_Adv.ecp"
          wa_url: "http://test.com/server"
          url: "http://test.com:6080/arcgis"
          domain_name: "test.com"
          services:
            - name: "map_bv"
              folder: ""
              type: "MapServer"
              definition_file: "C:/temp/data/map_bv.sd"
              properties:
                maxInstancesPerNode: 4
        data_store:
          setup: "C:\\temp\\setups\\ArcGIS_DataStore\\Setup.exe"
        portal:
          setup: "C:\\temp\\setups\\Portal_for_ArcGIS\\Setup.exe"
          authorization_file: "C:\\temp\\auth_files\\Portal_for_ArcGIS\\Portal_100.ecp"
          wa_url: "https://test.com/portal"
          url: "https://test.com:7443/arcgis"
          domain_name: "test.com"
        web_adaptor:
          setup: "C:\\temp\\setups\\WebAdaptorIIS\\Setup.exe"
    excludes:
      - centos-6.7
      - centos-7.1
      - centos-7.2
      - ubuntu-14.04
      - ubuntu-16.04
      - opensuse-13.2

  - name: webgis-linux
    driver:
      network:
        - ["forwarded_port", {guest: 6080, host: 26080}]
        - ["forwarded_port", {guest: 6443, host: 26443}]
        - ["forwarded_port", {guest: 7443, host: 27443}]
      synced_folders:
        - ["/net/twoball/twoball3/daily/ArcGISServer/CD_Linux", "/tmp/server-cd"]
        - ["/net/twoball/twoball3/daily/ArcGISDataStore/CD_Linux", "/tmp/data-store-cd"]
        - ["/net/twoball/twoball3/daily/ArcGISPortal/CD_Linux", "/tmp/portal-cd"]
        - ["/net/twoball/twoball3/daily/WebAdaptor/CD_Linux", "/tmp/web-adaptor-cd"]
        - ["/net/metro/Released/Authorization_Files/Version10.5/ArcGIS_Server/Advanced", "/tmp/auth_files/ArcGISServer"]
        - ["/net/metro/Released/Authorization_Files/Version10.5/Portal_for_ArcGIS", "/tmp/auth_files/ArcGISPortal"]
    run_list:
      - recipe[arcgis-server::system]
      - recipe[esri-tomcat]
      - recipe[iptables]
      - recipe[arcgis-server::iptables]
      - recipe[arcgis-server::server]
      - recipe[arcgis-server::server_wa]
      - recipe[arcgis-server::datastore]
      - recipe[arcgis-server::portal]
      - recipe[arcgis-server::portal_wa]
      - recipe[arcgis-server::federation]
    attributes:
      java:
        install_flavor: "oracle"
        jdk_version: "8"
        oracle:
          accept_oracle_download_terms: true
      arcgis:
        version: "10.5"
        hosts:
          test.com: ""
        server:
          setup: "/tmp/server-cd/Setup"
          authorization_file: "/tmp/auth_files/ArcGISServer/Server_Ent_Adv.ecp"
          wa_url: "http://test.com/server"
          url: "http://test.com:6080/arcgis"
          domain_name: "test.com"
        data_store:
          setup: "/tmp/data-store-cd/Setup"
        portal:
          setup: "/tmp/portal-cd/Setup"
          authorization_file: "/tmp/auth_files/ArcGISPortal/Portal_100.ecp"
          wa_url: "https://test.com/portal"
          url: "https://test.com:7443/arcgis"
          domain_name: "test.com"
        web_adaptor:
          setup: "/tmp/web-adaptor-cd/Setup"
        web_server:
          webapp_dir: "/opt/tomcat_arcgis/webapps"
    excludes:
      - windows-2012r2
      - windows-2008r2
      - windows-7
      - windows-81
      - windows-10
