---
driver:
  name: vagrant
  customize:
    memory: 6144
    cpuexecutioncap: 50

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

platforms:
  - name: windows-2012r2
  - name: windows-2008r2
  - name: windows-7
  - name: windows-81
  - name: windows-10
  - name: centos-6.7
  - name: centos-7.1
  - name: centos-7.2
  - name: ubuntu-14.04
  - name: opensuse-13.2

suites:
  - name: desktop
    driver:
      synced_folders:
        - ["/windows_setups/ArcGIS_Desktop", "C:/temp/setups/ArcGIS_Desktop"]
        - ["/net/metro/Released/Authorization_Files/Version10.5/ArcGIS_Desktop_Advanced_SU", "C:/temp/auth_files/ArcGIS_Desktop"]
    run_list:
      #- recipe[ms_dotnet::ms_dotnet4]
      - recipe[arcgis-desktop]
    attributes:
      #ms_dotnet:
        #v4:
          #version: "4.5.1"
      arcgis:
        version: "10.5"
        desktop:
          setup: "C:\\temp\\setups\\ArcGIS_Desktop\\Setup.exe"
          authorization_file: "C:\\temp\\auth_files\\ArcGIS_Desktop\\DTAdvanced.prvc"
          software_class: "Viewer"
          seat_preference: "Fixed"
          desktop_config: true
    excludes:
      - centos-6.7
      - centos-7.1
      - centos-7.2
      - ubuntu-14.04
      - opensuse-13.2

  - name: licensemanager
    driver:
      synced_folders:
        - ["/windows_setups/LicenseManager", "C:/temp/setups/LicenseManager"]
    run_list:
        - recipe[arcgis-desktop::licensemanager]
    attributes:
      arcgis:
        version: "10.4"
        licensemanager:
          setup: "C:\\temp\\setups\\LicenseManager\\Setup.exe"
    excludes:
      - centos-6.7
      - centos-7.1
      - centos-7.2
      - ubuntu-14.04
      - opensuse-13.2

  - name: licensemanager-linux
    driver:
      synced_folders:
        - ["/net/twoball/twoball3/daily/LicenseManager/CD_Linux", "/tmp/licensemanager-cd"]
    run_list:
        - recipe[arcgis-desktop::licensemanager]
    attributes:
      arcgis:
        version: "10.4"
        licensemanager:
                setup: "/tmp/licensemanager-cd/Setup"
    excludes:
      - windows-2012r2
      - windows-2008r2
      - windows-7
      - windows-81
      - windows-10
