---
driver:
  name: vagrant
  customize:
    memory: 6144
    cpuexecutioncap: 50

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

platforms:
  - name: windows-2012r2
  - name: windows-2008r2
  - name: windows-7
  - name: windows-81
  - name: windows-10

suites:
  - name: geoevent
    driver:
      network:
        - ["forwarded_port", {guest: 6080, host: 16080}]
        - ["forwarded_port", {guest: 6443, host: 16443}]
        - ["forwarded_port", {guest: 7443, host: 17443}]
      synced_folders:
        - ["/windows_setups/ArcGIS_Server", "C:/temp/setups/ArcGIS_Server"]
        - ["/windows_setups/GeoEvent", "C:/temp/setups/GeoEvent"]
        - ["/net/metro/Released/Authorization_Files/Version10.5/ArcGIS_Server/Advanced", "C:/temp/auth_files/ArcGIS_Server"]
    run_list:
      - recipe[arcgis-server::system]
      - recipe[arcgis-server::iis]
      - recipe[arcgis-server::server]
      - recipe[arcgis-geoevent]
    attributes:
      arcgis:
        version: "10.5"
        hosts:
          test.com: ""
        server:
          setup: "C:\\temp\\setups\\ArcGIS_Server\\Setup.exe"
          authorization_file: "C:\\temp\\auth_files\\ArcGIS_Server\\Server_Ent_Adv.ecp"
          url: "http://test.com:6080/arcgis"
          domain_name: "test.com"
        geoevent:
          setup: "C:\\temp\\setups\\GeoEvent\\Setup.exe"
